```{r message=FALSE}
source("util.R")
knitr::opts_chunk$set(fig.height=3, warning=FALSE)
source("data.R")
location <- "Monroe"
q <- quote(State=='Florida' & County=='Monroe')
#monroe <- zoo.nyt(eval(q))
monroe <- subset(zoo.jhu.US(eval(q)), confirmed > 0)
pop <- get.pop.US(eval(q))
# local.data <- NYT.COUNTIES %>% filter(eval(q)) %>% inner_join(US.POP)
local.data <- JHU.US %>% filter(eval(q)) %>% inner_join(US.POP)
local.num <- window(zoo.metrics(local.data), start="2020-03-15")
local <- local.num/pop*1e6
```

```{r child="child/Q1.Rmd"}
```

### Q2: How dangerous is it now?

The following numbers evaluate "danger #2" in
<a href="../risk/two-dangers.html">this split of covid danger</a>.

For context, about <b>one death per week</b> is the rate of 
pneumonia/flu deaths in the Keys (based on Florida rates).

Covid deaths
<sup>
[ * ](https://ourworldindata.org/coronavirus#deaths-from-covid-19-background)
</sup>
per week:<br>
```{r, fig.width=11}
autoplot.weekly.bar(weekly.deltas(monroe$deaths)) +
  scale_y_continuous(breaks=0:max(monroe$deaths))
```

See [a historical perspective](../risk/history.html) for a broad context.

<small>
[ * What is counted as a death from COVID-19?](https://ourworldindata.org/coronavirus#deaths-from-covid-19-background)
</small>

<!--
### Q3: Is coronavirus <a href="https://en.wikipedia.org/wiki/Endemic_(epidemiology)">endemic</a> yet?

% of population dead due to COVID
<br>
```{r, warning=FALSE, message=FALSE, fig.width=15, fig.height=4}
Middlesex <- zoo.jhu.US.micro(State=='Massachusetts' & County=='Middlesex')$deaths/1e6
fracmort <- merge(local=local$deaths/1e6, fav.fracmort(), Middlesex)
names(fracmort)[which(names(fracmort)=='local')] <- location

autoplot(fracmort, facet=NULL) +
  labs(x="Date", y="% dead of population", color="Region") +
  scale_x_eow(fracmort) +
  scale_y_continuous(limits=c(0,0.003), labels=scales::percent_format(accuracy=0.1))
```

### Q4: Can the Keys "beat" coronavirus?

**Answer: Apparently not.**

<a href="about.html">What makes the Keys an interesting case for study?</a>

Weekly covid deaths
<sup>
[ * ](https://ourworldindata.org/coronavirus#deaths-from-covid-19-background)
</sup>
per million of "winning" counties
compared with
2% and 1% of Keys cases per million:<br>
```{r message=FALSE, fig.width=13, fig.height=6}
asof <- end(monroe)
weekly.deaths <- function(country) {
  weekly.deltas(window(zoo.jhu.global.micro(country),end=asof))$deaths
}
taiwan <- weekly.deltas(window(zoo.jhu.global(Country=='Taiwan*'),end=asof)/23.8)
monroe.micro <- weekly.deltas(monroe$confirmed/pop*1e6)
winners <- window(merge(
  `2% Keys cases`= 0.02*monroe.micro,
  `1% Keys cases`= 0.01*monroe.micro,
  `Trinidad&Tobago`=weekly.deaths('Trinidad and Tobago'),
  `New Zealand`=weekly.deaths('New Zealand'),
#  `Australia`=weekly.deaths('Australia'),
  Singapore=weekly.deaths('Singapore'),
  Japan=weekly.deaths('Japan'),
  Korea=weekly.deaths('Korea, South'),
  `Taiwan`=taiwan$deaths
), start="2020-03-01")
autoplot(winners, facet=NULL) +
  geom_point() +
  scale_x_eow(winners) +
  xlab("2020") +
  ylab("Weekly COVID Deaths Per Million")
```
-->


```{r child="child/check.Rmd"}
```

