```{r message=FALSE}
source("util.R")
source("data.R")
location <- "San Francisco Metro Area"
pick <- c(
  06075) # SF
# local.data <- NYT.COUNTIES %>% filter(FIPS %in% pick) %>% inner_join(US.POP)
local.data <- JHU.US %>% filter(FIPS %in% pick) %>% inner_join(US.POP)
stopifnot(all(pick %in% local.data$FIPS))
pop <- get.pop.US(FIPS %in% pick)
local.num <- window(zoo.metrics(local.data), start="2020-03-15")
local <- local.num/pop*1e6
```

`r format(pop/1e6, digits=2)` million inhabitants of `r unique(local.data$County)` counties

<div>Top three questions:</div>
<ul>
<li>Q1: Is an outbreak starting?</li>
<li>Q2: How dangerous is it now?</li>
<li>Q3: 
  How close is `r location` to [herd immunity](../hit.html)?
</li>
</ul>

```{r child="child/Q1.Rmd"}
```

```{r child="child/Q2.Rmd"}
```

```{r message=FALSE, warning=FALSE}
fracmort <- merge(fav.fracmort(), local=local$deaths/1e6)
names(fracmort)[which(names(fracmort)=='local')] <- location
```

```{r child="child/Q3.Rmd"}
```

#### Data Check

```{r child="child/check.Rmd"}
```

